config/routes.rb
Rails.application.routes.draw do

  root 'session#new'

  resources :stocks
  # resources :bitcoins

  #get bitcoins
  get "/users/:id/bitcoins" => "bitcoins#show", as: 'bitcoins_show'
  post "/users/:id/bitcoins/:pricebcoin" => "bitcoins#create", as: 'bitcoins_create'
  post "/users/:id/bitcoins/submit/:id" => "bitcoins#destroy", as: 'bitcoins_delete'

  # This is the stock API lookup results page
  # post "/portfolios/:id/shares/search" => "shares#search", as: 'shares_search'
  get "/portfolios/:id/shares/search/submit" => "shares#search", as: 'shares_search'

  # Add the searched share to the portfolio (from the results page)
  post  "/portfolios/:id/shares/:ticker/add" => "shares#create", as: 'share_add'

  # Updating the balance
  # get "/users/:id/balance/operation"
  post "/users/:id/balance" => "users#balance", as: 'user_balance'


  resources :portfolios do
    resources :shares
  end

  resources :users, except: [:index]




  get "/login" => 'session#new' #login form
  post "/login" => 'session#create' #form submits here to perform login
  delete "/login" => 'session#destroy' #logout (delete session)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/share.rb
class Share < ApplicationRecord
  has_and_belongs_to_many :portfolios
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController

  def index
  end

  def search
    stock = StockQuote::Stock.quote(params[:symbol])
    puts "The Stock is #{stock}"
    @price = stock.latest_price
    @company = stock.company_name
    @symbol = stock.symbol
    @market_cap = stock.market_cap
    @year_high = stock.week52_high
    @year_low = stock.week52_low
    @ytd_change = "#{(stock.ytd_change*100).round(2)}%"
    @logo = StockQuote::Stock.logo(params[:symbol])

    #Chart data from API
    @chart = StockQuote::Stock.chart(params[:symbol], '1y')

    #Obtaining array of 12 month prices and dates for chart
    @list_of_prices = []
    @list_of_dates = []
    @chart.chart.each do |price|
      @list_of_prices << price["close"]
      @list_of_dates << price["label"]
    end

    @list_of_prices = @list_of_prices.to_json
    @list_of_dates = @list_of_dates.to_json

    # @chart  = StockQuote::Stock.chart(params[:symbol], '5y')
    # @profit = stock.grossProfit
    # @peers = stock.peers
    current_portfolio = Portfolio.find params[:id]
    @stock_in_portfolio_id = current_portfolio.shares.find_by(ticker: params[:symbol])
  end

  def new
    @share = Share.new
  end

  def create
    # raise 'hell'
    if (params[:buy].to_i * params[:price].to_i) < @current_user.funds
      share = Share.create(
        name: params[:symbol],
        ticker: params[:ticker],
        quantity: params[:buy].to_i,
        price: params[:price].to_i
      )
      p = Portfolio.find(params[:id])
      p.shares << share

      @current_user.funds -= (params[:buy].to_i * params[:price].to_i)
      @current_user.save()

      redirect_to portfolio_path(params[:id])
    else
      flash[:notice] = "Insufficient Funds"
      redirect_to shares_search_path(params[:id], symbol: params[:ticker]), method: 'get'

    end

  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    share = Share.find params[:id]
    portfolio = Portfolio.find(params[:portfolio_id])
    owned_qty = share.quantity
    sell_qty = params[:sell].to_i

    if (owned_qty - sell_qty) == 0
      # Selling down all holdings, delete from the database
      portfolio.shares.delete(share)
      redirect_to portfolio_path(params[:portfolio_id])

      #Logic to add funds
      @current_user.funds += (sell_qty * share.price)
      @current_user.save()
    elsif (owned_qty - sell_qty) > 0
      # Partial sell down of portfolio
      share.quantity -= sell_qty
      share.save()

      #logic to add funds to account
      @current_user.funds += (sell_qty * share.price)
      @current_user.save()
      redirect_to portfolio_path(params[:portfolio_id])
    else
      #Error you do not have enough units
      flash[:notice] = "You don't have enough of this stock"
      # raise 'hell'
      redirect_to shares_search_path(params[:portfolio_id], symbol: share.ticker), method: 'get'
    end


  end


end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/shares/create.html.erb
<h1>Shares#create</h1>
<p>Find me in app/views/shares/create.html.erb</p>

app/views/shares/destroy.html.erb
<h1>Shares#destroy</h1>
<p>Find me in app/views/shares/destroy.html.erb</p>

<h3>testing</h3>

app/views/shares/edit.html.erb
<h1>Shares#edit</h1>
<p>Find me in app/views/shares/edit.html.erb</p>

app/views/shares/index.html.erb
index.html.erb

app/views/shares/new.html.erb
<h2>Add a share to your portfolio</h2>

<% if flash[:errors].present? -%>
  <strong>Please correct the following errors: </strong>
  <ol>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @share do |f| %>

  <%= f.label :ticker %>
  <%= f.text_field :ticker %>
  <br>

  <%= f.submit %>
<% end %>

app/views/shares/search.html.erb
<h3>
<%= link_to "Back to Dashboard", user_path %>
</h3>
<h3>
<%= form_tag share_add_path(params[:id],  @symbol, symbol: @company, price: @price) do %>
  BUY <input type="text" name="buy" placeholder="Amount">
  <input type="submit" value="Buy">
<% end %>

<br>
</h3>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<h3>
  <% if @stock_in_portfolio_id.present? %>
    <%= form_tag portfolio_share_path(params[:id], @stock_in_portfolio_id), method: :delete do %>
      SELL <input type="text" name="sell" placeholder="Amount">
      <input type="submit" value="Sell">
    <% end %>
  <% end %>
<br>
</h3>


<h2>Share Information</h2>

<%= image_tag(@logo.url) %>
<br>
<br>
Company: <%= @company %>
<br>
<br>
Symbol: <%= @symbol %>
<br>
<br>
Last Price: $<%= @price %>
<br>
<br>
Market Cap:<%= number_to_currency(@market_cap) %>
<br>
<br>
52 Week High: $<%= @year_high %>
<br>
<br>
52 Week Low: $<%= @year_low %>
<br>
<br>
YTD Change(%): <%= @ytd_change %>
<br>




<!-- Chart.js practice  -->

<canvas id="myChart" width="80" height="80"></canvas>
<script>
var myJsDates = <%=raw @list_of_dates%>;
var myJsPrices = <%=raw @list_of_prices%>;
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: myJsDates,
        datasets: [{
            label: 'Share Price',
            data: myJsPrices,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: false
                }
            }]
        }
    }
});
</script>

app/views/shares/show.html.erb
<h2>show shares</h2>

app/views/shares/update.html.erb
<h1>Shares#update</h1>
<p>Find me in app/views/shares/update.html.erb</p>