config/routes.rb
Rails.application.routes.draw do

  root 'session#new'

  resources :stocks
  # resources :bitcoins

  #get bitcoins
  get "/users/:id/bitcoins" => "bitcoins#show", as: 'bitcoins_show'
  post "/users/:id/bitcoins/:pricebcoin" => "bitcoins#create", as: 'bitcoins_create'
  post "/users/:id/bitcoins/submit/:id" => "bitcoins#destroy", as: 'bitcoins_delete'

  # This is the stock API lookup results page
  # post "/portfolios/:id/shares/search" => "shares#search", as: 'shares_search'
  get "/portfolios/:id/shares/search/submit" => "shares#search", as: 'shares_search'

  # Add the searched share to the portfolio (from the results page)
  post  "/portfolios/:id/shares/:ticker/add" => "shares#create", as: 'share_add'

  # Updating the balance
  # get "/users/:id/balance/operation"
  post "/users/:id/balance" => "users#balance", as: 'user_balance'


  resources :portfolios do
    resources :shares
  end

  resources :users, except: [:index]




  get "/login" => 'session#new' #login form
  post "/login" => 'session#create' #form submits here to perform login
  delete "/login" => 'session#destroy' #logout (delete session)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/stock.rb
class Stock < ApplicationRecord
  has_and_belongs_to_many :portfolios
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def new
  end

  def create
  end

  def index
    @stocks = Stock.all
  end

  def show
    @stock = Stock.find params[:id]
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/create.html.erb
<h1>Stocks#create</h1>
<p>Find me in app/views/stocks/create.html.erb</p>

app/views/stocks/destroy.html.erb
<h1>Stocks#destroy</h1>
<p>Find me in app/views/stocks/destroy.html.erb</p>

app/views/stocks/edit.html.erb
<h1>Stocks#edit</h1>
<p>Find me in app/views/stocks/edit.html.erb</p>

app/views/stocks/index.html.erb
<h3>
<%= link_to "All Portfolios", portfolios_path %>
</h3>


<h2>All Stocks</h2>



<ul>
<% @stocks.each do |stock| %>

<li>
  <%= link_to "#{stock.name}, #{stock.ticker}, #{stock.price}, #{stock.description}", stock_path(stock.id)%>
</li>

<% end %>
</ul>

app/views/stocks/new.html.erb
<h1>Stocks#new</h1>
<p>Find me in app/views/stocks/new.html.erb</p>

app/views/stocks/show.html.erb
<h3>
  <%= link_to "Your Portfolios", user_path %>
</h3>



<h2><%= "#{@stock.name} Stock Information" %></h2>


<strong>Name:</strong> <%= @stock.name %>
<br>
<strong>Ticker</strong>: <%= @stock.ticker %>
<br>
<strong>Price</strong>: <%= @stock.price %>
<br>
<strong>Description</strong>: <%= @stock.description %>
<br>

app/views/stocks/update.html.erb
<h1>Stocks#update</h1>
<p>Find me in app/views/stocks/update.html.erb</p>