config/routes.rb
Rails.application.routes.draw do

  root 'session#new'

  resources :stocks
  # resources :bitcoins

  #get bitcoins
  get "/users/:id/bitcoins" => "bitcoins#show", as: 'bitcoins_show'
  post "/users/:id/bitcoins/:pricebcoin" => "bitcoins#create", as: 'bitcoins_create'
  post "/users/:id/bitcoins/submit/:id" => "bitcoins#destroy", as: 'bitcoins_delete'

  # This is the stock API lookup results page
  # post "/portfolios/:id/shares/search" => "shares#search", as: 'shares_search'
  get "/portfolios/:id/shares/search/submit" => "shares#search", as: 'shares_search'

  # Add the searched share to the portfolio (from the results page)
  post  "/portfolios/:id/shares/:ticker/add" => "shares#create", as: 'share_add'

  # Updating the balance
  # get "/users/:id/balance/operation"
  post "/users/:id/balance" => "users#balance", as: 'user_balance'


  resources :portfolios do
    resources :shares
  end

  resources :users, except: [:index]




  get "/login" => 'session#new' #login form
  post "/login" => 'session#create' #form submits here to perform login
  delete "/login" => 'session#destroy' #logout (delete session)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord

  has_many :portfolios

  has_and_belongs_to_many :bitcoins

  has_many :shares, through: 'portfolios'

  has_secure_password

  #this is a method in the model that will be available to call whenever this model is being used
  def all_assets
    result = {}

    #create a new key value in the result hash by getting an array of all the shares a user owns
    # (we set up that users have many shares through portfolios and sum them)
    result[:stock_value] = self.shares.uniq.reduce(0) do |sum, current|
      sum + current.price * current.quantity
    end

    #Needed to get the current market price of bitcoin
    require 'json'
    url = 'https://api.coindesk.com/v1/bpi/currentprice.json'
    raw_response = HTTParty.get(url)
    response = JSON.parse(raw_response)
    @current_bitcoin_price = response['bpi']['USD']['rate'].tr(',', '').to_f.round(2)

    #Get the current value of bitcoin the user has
    if self.bitcoins.present?
      user_bcoin = self.bitcoins
      result[:bitcoin] = user_bcoin[0][:quantity] * @current_bitcoin_price
    else
      result[:bitcoin] = 0
    end



    result[:net_worth] = result[:bitcoin] + result[:stock_value] + self.funds

    result
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    @user.funds = params[:user][:funds].to_i
    @user.save()

    if @user.persisted?
      #log them in automatically
      session[:user_id] = @user.id

      redirect_to user_path(@user.id)
    else
      flash[:errors] = @user.errors.full_messages

      render :new
    end
  end

  def show
    #This is where the user's portfolio is shown
    @user_portfolio = @current_user.portfolios

  end

  def balance
  if params[:operator] == '+'
    funds = User.find params[:id]
    funds.funds += params[:deposit].to_i
  else
    funds = User.find params[:id]
    funds.funds -= params[:withdraw].to_i
  end
  funds.save()

  redirect_to user_path(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h2>Create an Account!</h2>

<% if flash[:errors].present? %>
  <strong>Please correct the following errors: </strong>
  <ol>
    <% flash[:errors].each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.label :password %>
  <%= f.text_field :password %>
  <br>

  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>
  <br>

  <%= f.label :funds %>
  <%= f.number_field :funds %>
  <br>

  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<%= form_tag user_balance_path(@current_user.id, operator: '+') do %>
  Deposit Funds: <input type="text" name="deposit" placeholder="Amount">
  <input type="submit" value="Deposit">
<% end %>
<br>
<%= form_tag user_balance_path(@current_user.id, operator: '-') do %>
  Withdraw Funds: <input type="text" name="withdraw" placeholder="Amount">
  <input type="submit" value="Withdraw">
<% end %>
<br>
<br>
<hr>

<h3>Create New Portfolio</h3>
<%= link_to "Create New Portfolio", new_portfolio_path %>


<h2><%= "#{@current_user.name}'s Portfolio" %></h2>



<ul>
  <% @user_portfolio.each do |portfolio| %>
    <li>
      <%= link_to "#{portfolio.title}", portfolio_path(portfolio.id) %>
    </li>
  <% end %>
</ul>

<hr>
<br>
<h1>
  <%= link_to "View Bitcoin Trading", bitcoins_show_path(@current_user.id) %>
</h1>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>