config/routes.rb
Rails.application.routes.draw do

  root 'session#new'

  resources :stocks
  # resources :bitcoins

  #get bitcoins
  get "/users/:id/bitcoins" => "bitcoins#show", as: 'bitcoins_show'
  post "/users/:id/bitcoins/:pricebcoin" => "bitcoins#create", as: 'bitcoins_create'
  post "/users/:id/bitcoins/submit/:id" => "bitcoins#destroy", as: 'bitcoins_delete'

  # This is the stock API lookup results page
  # post "/portfolios/:id/shares/search" => "shares#search", as: 'shares_search'
  get "/portfolios/:id/shares/search/submit" => "shares#search", as: 'shares_search'

  # Add the searched share to the portfolio (from the results page)
  post  "/portfolios/:id/shares/:ticker/add" => "shares#create", as: 'share_add'

  # Updating the balance
  # get "/users/:id/balance/operation"
  post "/users/:id/balance" => "users#balance", as: 'user_balance'


  resources :portfolios do
    resources :shares
  end

  resources :users, except: [:index]




  get "/login" => 'session#new' #login form
  post "/login" => 'session#create' #form submits here to perform login
  delete "/login" => 'session#destroy' #logout (delete session)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/bitcoin.rb
class Bitcoin < ApplicationRecord

  has_and_belongs_to_many :users
end

app/controllers/bitcoins_controller.rb
class BitcoinsController < ApplicationController
  def new
  end

  def create
    if (params[:buy].to_i * params[:pricebcoin].to_i) < @current_user.funds
      bitcoin = Bitcoin.create(
        quantity: params[:buy].to_i,
        price: params[:pricebcoin].to_i
      )
      u = User.find(params[:id])
      u.bitcoins << bitcoin

      @current_user.funds -= (params[:buy].to_i * params[:pricebcoin].to_i)
      @current_user.save()

      redirect_to bitcoins_show_path(params[:id])

    else
      flash[:notice] = "Insufficient Funds"
      redirect_to bitcoins_show_path(params[:id])

    end
  end

  def show
    ###### BITCOIN LOGIC #############

    # Here we get the Data using HTTParty
    # We then convert it from JSON to ruby hash
    require 'json'
    url = 'https://api.coindesk.com/v1/bpi/currentprice.json'

    raw_response = HTTParty.get(url)
    response = JSON.parse(raw_response)
    @current_bitcoin_price = response['bpi']['USD']['rate'].tr(',', '').to_f.round(2)

    ## Show any user bitcoins
    current_user = User.find params[:id]
    user_bitcoins = current_user.bitcoins

    if user_bitcoins.present?
      @user_bitcoin_qty = user_bitcoins[0][:quantity]
      @bitcoin_id = user_bitcoins[0][:id]
      bitcoin_in_question = Bitcoin.find @bitcoin_id
      @bitcoin_return = (((@current_bitcoin_price / bitcoin_in_question[:price])-1)*100).round(2)
      @user_id_sell = params[:id]
    end


  end

  def edit
  end

  def update
  end

  def destroy
    bitcoin = Bitcoin.find params[:id]
    user = @current_user
    owned_qty = bitcoin.quantity
    sell_qty = params[:sell].to_i

    #sell down whole portfolio

    if (owned_qty - sell_qty) == 0
      user.bitcoins.delete(bitcoin)
      @current_user.funds += (sell_qty * bitcoin.price)
      @current_user.save()

      redirect_to bitcoins_show_path(@current_user.id)
    elsif (owned_qty - sell_qty) > 0
      bitcoin.quantity -= sell_qty
      bitcoin.save()
      @current_user.funds += (sell_qty * bitcoin.price)
      @current_user.save()
      redirect_to bitcoins_show_path(@current_user.id)
    else
      flash[:notice] = "Bummer man you don't have enough bitcoins"
      redirect_to bitcoins_show_path(@current_user.id)
    end
  end
end

app/helpers/bitcoins_helper.rb
module BitcoinsHelper
end

app/views/bitcoins/create.html.erb
<h1>Bitcoins#create</h1>
<p>Find me in app/views/bitcoins/create.html.erb</p>

app/views/bitcoins/destroy.html.erb
<h1>Bitcoins#destroy</h1>
<p>Find me in app/views/bitcoins/destroy.html.erb</p>

app/views/bitcoins/edit.html.erb
<h1>Bitcoins#edit</h1>
<p>Find me in app/views/bitcoins/edit.html.erb</p>

app/views/bitcoins/new.html.erb
<h1>Bitcoins#new</h1>
<p>Find me in app/views/bitcoins/new.html.erb</p>

app/views/bitcoins/show.html.erb
<h3>
<%= link_to "Back to Dashboard", user_path %>
</h3>

<hr>

<h2>
  Current Price of Bitcoin ($USD):   <%= number_to_currency(@current_bitcoin_price) %>
</h2>

<div id="bitcoin_logo">
<%= image_tag("bitcoin-logo.png",  alt: "bitcoin logo", :size => "150x150") %>
</div>

<h3>
<%= form_tag bitcoins_create_path(params[:id], pricebcoin: @current_bitcoin_price) do %>
  BUY <input type="text" name="buy" placeholder="Amount">
  <input type="submit" value="Buy">
<% end %>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<br>
</h3>

<!--  Sell Bitcoins-->
<h3>
  <% if @user_bitcoin_qty.present? %>
    <%= form_tag bitcoins_delete_path(@user_id_sell, @bitcoin_id) do %>
      SELL <input type="text" name="sell" placeholder="Amount">
      <input type="submit" value="Sell">
    <% end %>
  <% end %>
<br>
</h3>

<h1>Amount of bitcoins: <%= @user_bitcoin_qty %></h1>

<h2>

  <% if @user_bitcoin_qty.present? %>
    Bitcoin return (%):
    <%= @bitcoin_return %>

  <% end %>
<br>
</h2>

app/views/bitcoins/update.html.erb
<h1>Bitcoins#update</h1>
<p>Find me in app/views/bitcoins/update.html.erb</p>